#!/usr/bin/env bash
set -Eeuo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "bootstrap.sh must run as root" >&2
  exit 1
fi

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
export DEBIAN_FRONTEND=noninteractive

apt-get update -qq
apt-get install -y --no-install-recommends \
  auditd ca-certificates curl jq nginx openssl postgresql postgresql-client \
  python3 python3-pip python3-venv ufw

if ! id orders-api >/dev/null 2>&1; then
  useradd --system --home-dir /var/lib/orders-api --create-home --shell /usr/sbin/nologin orders-api
fi

install -d -o root -g root -m 0755 /opt/orders-api
install -o root -g root -m 0644 "${SCRIPT_DIR}/app/app.py" /opt/orders-api/app.py
install -o root -g root -m 0644 "${SCRIPT_DIR}/app/requirements.txt" /opt/orders-api/requirements.txt

python3 -m venv /opt/orders-api/.venv
/opt/orders-api/.venv/bin/pip install --disable-pip-version-check --no-cache-dir -r /opt/orders-api/requirements.txt

DB_PASSWORD="$(openssl rand -hex 24)"

if ! runuser -u postgres -- psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='orders_app'" | grep -qx 1; then
  runuser -u postgres -- createuser --login orders_app
fi
runuser -u postgres -- psql -v ON_ERROR_STOP=1 -c "ALTER ROLE orders_app WITH LOGIN PASSWORD '${DB_PASSWORD}';"

if ! runuser -u postgres -- psql -tAc "SELECT 1 FROM pg_database WHERE datname='orders_benchmark'" | grep -qx 1; then
  runuser -u postgres -- createdb --owner=orders_app orders_benchmark
fi
runuser -u postgres -- psql -v ON_ERROR_STOP=1 -c "ALTER DATABASE orders_benchmark OWNER TO orders_app;"

PGPASSWORD="${DB_PASSWORD}" psql -v ON_ERROR_STOP=1 \
  -h 127.0.0.1 -U orders_app -d orders_benchmark <<'SQL'
CREATE TABLE IF NOT EXISTS orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer text NOT NULL CHECK (length(btrim(customer)) > 0),
  amount numeric(12,2) NOT NULL CHECK (amount > 0),
  status text NOT NULL CHECK (status IN ('pending', 'paid', 'cancelled')),
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO orders (id, customer, amount, status, created_at) VALUES
  (1, 'Acme Industries', 125.50, 'pending',   '2026-08-01T10:00:00Z'),
  (2, 'Globex Corp',      89.99, 'paid',      '2026-08-01T11:00:00Z'),
  (3, 'Initech',         240.00, 'pending',   '2026-08-01T12:00:00Z'),
  (4, 'Umbrella Labs',    19.95, 'cancelled', '2026-08-01T13:00:00Z'),
  (5, 'Soylent Systems',  77.70, 'paid',      '2026-08-01T14:00:00Z')
ON CONFLICT (id) DO UPDATE SET
  customer = EXCLUDED.customer,
  amount = EXCLUDED.amount,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at;

SELECT setval(pg_get_serial_sequence('orders', 'id'), (SELECT max(id) FROM orders), true);
SQL

install -d -o root -g orders-api -m 0750 /etc/orders-api
cat >/etc/orders-api/orders.env <<EOF
DATABASE_URL=postgresql://orders_app:${DB_PASSWORD}@127.0.0.1:5432/orders_benchmark
APP_PORT=3000
EOF
chown root:orders-api /etc/orders-api/orders.env
chmod 0640 /etc/orders-api/orders.env

cat >/etc/orders-api/pgpass <<EOF
127.0.0.1:5432:orders_benchmark:orders_app:${DB_PASSWORD}
EOF
chown orders-api:orders-api /etc/orders-api/pgpass
chmod 0600 /etc/orders-api/pgpass

install -d -o orders-api -g orders-api -m 0750 /var/backups/orders-api /var/log/orders-api

cat >/etc/systemd/system/orders-api.service <<'UNIT'
[Unit]
Description=Orders benchmark API
After=network-online.target postgresql.service
Wants=network-online.target

[Service]
Type=simple
User=orders-api
Group=orders-api
EnvironmentFile=/etc/orders-api/orders.env
WorkingDirectory=/opt/orders-api
ExecStart=/opt/orders-api/.venv/bin/gunicorn --workers 2 --bind 127.0.0.1:3000 --access-logfile - --error-logfile - app:app
Restart=on-failure
RestartSec=2s
TimeoutStopSec=15s
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/orders-api /var/log/orders-api

[Install]
WantedBy=multi-user.target
UNIT

cat >/etc/nginx/sites-available/orders-api <<'NGINX'
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 3s;
        proxy_read_timeout 15s;
    }
}
NGINX
rm -f /etc/nginx/sites-enabled/default
ln -sfn /etc/nginx/sites-available/orders-api /etc/nginx/sites-enabled/orders-api
nginx -t

cat >/usr/local/sbin/orders-backup <<'BACKUP'
#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

BACKUP_DIR=/var/backups/orders-api
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
TMP="${BACKUP_DIR}/.orders-${STAMP}.dump.tmp"
FINAL="${BACKUP_DIR}/orders-${STAMP}.dump"
export PGPASSFILE=/etc/orders-api/pgpass

mkdir -p "${BACKUP_DIR}"
chmod 0750 "${BACKUP_DIR}"
pg_dump -h 127.0.0.1 -U orders_app -d orders_benchmark -Fc -f "${TMP}"
pg_restore --list "${TMP}" >/dev/null
mv "${TMP}" "${FINAL}"
find "${BACKUP_DIR}" -maxdepth 1 -type f -name 'orders-*.dump' -mtime +7 -delete
printf '%s\n' "${FINAL}"
BACKUP
chown root:orders-api /usr/local/sbin/orders-backup
chmod 0750 /usr/local/sbin/orders-backup

cat >/etc/systemd/system/orders-backup.service <<'UNIT'
[Unit]
Description=Backup Orders benchmark database
After=postgresql.service

[Service]
Type=oneshot
User=orders-api
Group=orders-api
ExecStart=/usr/local/sbin/orders-backup
PrivateTmp=true
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/backups/orders-api
UNIT

cat >/etc/systemd/system/orders-backup.timer <<'UNIT'
[Unit]
Description=Daily Orders database backup

[Timer]
OnCalendar=*-*-* 02:17:00 UTC
Persistent=true
RandomizedDelaySec=5m

[Install]
WantedBy=timers.target
UNIT

cat >/etc/logrotate.d/orders-api-benchmark <<'LOGROTATE'
/var/log/orders-api/*.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    copytruncate
    create 0640 orders-api orders-api
}
LOGROTATE

systemctl daemon-reload
systemctl enable --now postgresql nginx orders-api.service orders-backup.timer
systemctl restart orders-api.service
systemctl reload nginx.service

while read -r ssh_port; do
  [[ -n "${ssh_port}" ]] && ufw allow "${ssh_port}/tcp" >/dev/null
done < <(sshd -T | awk '$1 == "port" { print $2 }' | sort -u)
ufw allow 'Nginx Full' >/dev/null
ufw default deny incoming >/dev/null
ufw default allow outgoing >/dev/null
ufw --force enable >/dev/null

(cd / && runuser -u orders-api -- /usr/local/sbin/orders-backup) >/dev/null

for _ in $(seq 1 30); do
  if curl -fsS http://127.0.0.1/health | jq -e '.status == "ok"' >/dev/null; then
    break
  fi
  sleep 1
done

curl -fsS http://127.0.0.1/health | jq -e '.status == "ok" and .database == "orders_benchmark"' >/dev/null
[[ "$(curl -fsS http://127.0.0.1/orders | jq 'length')" -eq 5 ]]
systemctl is-active --quiet orders-api.service nginx postgresql
systemctl is-enabled --quiet orders-api.service orders-backup.timer

install -d -o root -g root -m 0700 /var/lib/server-benchmark
date -u +%FT%TZ >/var/lib/server-benchmark/baseline-ready-at
echo "Baseline installation verified."
